stages:
  data_ingestion:
    cmd: ./.venv/bin/python ml_pipelines_with_DVC/src/data_ingestion.py
    deps:
      - ml_pipelines_with_DVC/src/data_ingestion.py
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: ./.venv/bin/python ml_pipelines_with_DVC/src/data_preprocessing.py
    deps:
      - ml_pipelines_with_DVC/src/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv

  feature_engineering:
    cmd: ./.venv/bin/python ml_pipelines_with_DVC/src/feature_engineering.py
    deps:
      - ml_pipelines_with_DVC/src/feature_engineering.py
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
    outs:
      - data/features/train_bow.csv
      - data/features/test_bow.csv

  model_building:
    cmd: ./.venv/bin/python ml_pipelines_with_DVC/src/model_building.py
    deps:
      - ml_pipelines_with_DVC/src/model_building.py
      - data/features/train_bow.csv
    outs:
      - model.pkl

  model_evaluation:
    cmd: ./.venv/bin/python ml_pipelines_with_DVC/src/model_evaluation.py
    deps:
      - ml_pipelines_with_DVC/src/model_evaluation.py
      - data/features/test_bow.csv
      - model.pkl
    metrics:
      - metrics.json
